# Generated by Django 3.1 on 2021-09-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210929_0756'),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
            preserve_default=False,
        ),
    ]
