version: '3'
services:
  db:
    image: postgres
    restart: always # reload when db container is down
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auction
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "15432:5432"

  redis:
    image: redis

  web:
    build:
      context: application
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./application:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  beat:
    restart: always
    build:
      context: application
      dockerfile: Dockerfile
    command: celery -A auction beat -l info --max-interval 600
    volumes:
      - ./application:/app
    depends_on:
      - web
  celery:
    restart: always
    build:
      context: application
      dockerfile: Dockerfile
    command: celery -A auction worker -l info
    volumes:
      - ./application:/app
    depends_on:
      - web

volumes:
  postgres-data: