version: '3'
services:
  db:
    image: postgres
    restart: always # reload when db container is down
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auction
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  redis:
    image: redis
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  celery:
    restart: always
    build:
      context: .
    command: celery -A auction worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web
