# Generated by Django 3.1 on 2021-09-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210929_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='buy_it_now',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
