# Generated by Django 3.1 on 2021-09-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210929_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='buy_it_now',
            new_name='buy_now_price',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='option',
            new_name='type',
        ),
    ]
