# Generated by Django 3.1 on 2021-09-30 12:31

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210930_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.IntegerField(choices=[('PENDING', 0), ('IN_PROGRESS', 1), ('CLOSED', 2)], default=auctions.models.AuctionStatusChoice['PENDING']),
        ),
        migrations.AlterField(
            model_name='auction',
            name='type',
            field=models.IntegerField(choices=[('DUTCH', 0), ('ENGLISH', 1)]),
        ),
    ]
