# Generated by Django 3.1 on 2021-10-01 09:24

import auctions.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210930_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='id',
        ),
        migrations.AddField(
            model_name='auction',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'IN_PROGRESS'), (2, 'CLOSED')], default=auctions.models.AuctionStatusChoice['PENDING']),
        ),
        migrations.AlterField(
            model_name='auction',
            name='type',
            field=models.IntegerField(choices=[(0, 'DUTCH'), (1, 'ENGLISH')]),
        ),
    ]
