# Generated by Django 3.1 on 2021-10-06 08:34

import auctions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0008_auto_20211001_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='type',
            field=models.IntegerField(choices=[(0, 'DUTCH'), (1, 'ENGLISH')], default=auctions.models.AuctionTypeChoice['ENGLISH']),
        ),
        migrations.CreateModel(
            name='AuctionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
