# Generated by Django 3.1 on 2021-10-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211006_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionhistory',
            old_name='price',
            new_name='new_price',
        ),
    ]
