# Generated by Django 3.1 on 2021-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='items')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
    ]
