# Generated by Django 3.1 on 2021-09-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutchAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('step', models.IntegerField()),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'IN PROGRESS'), (3, 'CLOSED')], default=1)),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frequency', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('step', models.IntegerField()),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'IN PROGRESS'), (3, 'CLOSED')], default=1)),
                ('buy_it_now', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
