# Generated by Django 3.1 on 2021-09-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('step', models.IntegerField()),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'IN PROGRESS'), (2, 'CLOSED')], default=0)),
                ('option', models.IntegerField(choices=[(0, 'ENGLISH'), (1, 'DUTCH')])),
                ('buy_it_now', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('frequency', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DutchAuction',
        ),
        migrations.DeleteModel(
            name='EnglishAuction',
        ),
    ]
