name: Auction CI/CD

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Set DJANGO_MODULE_SETTINGS
        run: export DJANGO_SETTINGS_MODULE="auction.development_settings"
      - name: Build docker-compose
        run: docker-compose up -d --build
      - name: Migrate database
        run: docker-compose run --rm --entrypoint='./manage.py migrate' web
      - name: Start curl test
        run: curl http://localhost:8000/lots/
      - name: Start pytest
        run: docker-compose run web pytest -rP
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
