name: Auction CI

on:
  push:
    branches: "*"
    
  workflow_dispatch:


jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.4
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-python@v2"
      with:
        python-version: "${{ matrix.python-version }}"
    
    - name: Build
      run: docker-compose up -d --build
    - name: Migrate
      run: docker-compose run --rm --entrypoint='./manage.py migrate' web  
    - name: curl
      run: curl http://localhost:8000/lots/
    - name: Tests
      run: docker-compose run web pytest auctions/ -rP
