name: Auction CI

on:
  push:
    branches: "*"
    
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker-compose up -d --build
      - name: Migrate
        run: docker-compose run --rm --entrypoint='./manage.py migrate' web  
      - name: curl
        run: curl http://localhost:8000/lots/
      - name: Tests
        run: docker-compose run web pytest auctions/ -rP
