name: Auction CI/CD
env:
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Build docker-compose
        run: docker-compose up -d --build
        working-directory: ./application
      - name: Migrate database
        run: docker-compose run --rm --entrypoint='./manage.py migrate' web
        working-directory: ./application
      - name: Start curl test
        run: curl http://localhost:8000/lots/
      - name: Start pytest
        run: docker-compose run web pytest -rP --ds=auction.development_settings
        working-directory: ./application

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Apply
        run: terraform apply -auto-approve
