name: Auction CI/CD


on:
  push:
    branches: "*"
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: "actions/checkout@v2"
    - name: Build docker compose
      run: docker-compose up -d --build
    - name: Migrate database
      run: docker-compose run --rm --entrypoint='./manage.py migrate' web
    - name: Curl test
      run: curl http://localhost:8000/lots/
    - name: Pytest
      run: docker-compose run web pytest auctions/ -rP
